-- Step 1
USE ROLE SYSADMIN;

CREATE WAREHOUSE SHOPSTREAM_WH
WAREHOUSE_SIZE = 'X-SMALL'
AUTO_SUSPEND = 30
AUTO_RESUME = TRUE
INITIALLY_SUSPENDED = TRUE
COMMENT = 'Primary warehouse for ShopStream dbt transformations';


-- Step 2
USE ROLE SECURITYADMIN;

-- Admin role for project administration
CREATE ROLE SHOPSTREAM_ADMIN
COMMENT = 'Admin role for ShopStream data platform';

-- dbt role with least privilege
CREATE ROLE SHOPSTREAM_DBT_ROLE
COMMENT = 'Role used by dbt to run transformations in ShopStream';

-- Grant role hierarchy
-- SHOPSTREAM_DBT_ROLE rolls up into SHOPSTREAM_ADMIN
-- SHOPSTREAM_ADMIN rolls up into SYSADMIN
GRANT ROLE SHOPSTREAM_DBT_ROLE TO ROLE SHOPSTREAM_ADMIN;
GRANT ROLE SHOPSTREAM_ADMIN TO ROLE SYSADMIN;

-- Step 3
USE ROLE SECURITYADMIN;

CREATE USER SHOPSTREAM_DBT_USER
    PASSWORD = '######'
    DEFAULT_ROLE = SHOPSTREAM_DBT_ROLE
    DEFAULT_WAREHOUSE = SHOPSTREAM_WH
    COMMENT = 'Service user for dbt transformations';

-- Assign the role to the user
GRANT ROLE SHOPSTREAM_DBT_ROLE TO USER SHOPSTREAM_DBT_USER;

-- Step 4
USE ROLE SYSADMIN;

-- RAW database: where COPY INTO lands data from S3
-- dbt never writes here, only reads
CREATE DATABASE SHOPSTREAM_RAW
COMMENT = 'Raw data loaded from S3 via COPY INTO. Never modified.';

-- DEV database: where dbt builds all transformed models
CREATE DATABASE SHOPSTREAM_DEV
COMMENT = 'Development environment for dbt transformations';


-- Step 5
USE ROLE SYSADMIN;

-- RAW schema inside RAW database
CREATE SCHEMA SHOPSTREAM_RAW.ECOMMERCE
COMMENT = 'Raw ecommerce data loaded from S3';

-- dbt layer schemas inside DEV database
CREATE SCHEMA SHOPSTREAM_DEV.BRONZE
COMMENT = 'Bronze layer: standardized raw data';

CREATE SCHEMA SHOPSTREAM_DEV.SILVER
COMMENT = 'Silver layer: business logic and modeled entities';

CREATE SCHEMA SHOPSTREAM_DEV.GOLD
COMMENT = 'Gold layer: star schema and business KPIs';

-- Step 6
USE ROLE SECURITYADMIN;

-- Give SHOPSTREAM_DBT_ROLE access to the warehouse
GRANT USAGE ON WAREHOUSE SHOPSTREAM_WH
TO ROLE SHOPSTREAM_DBT_ROLE;

-- Give READ ONLY access to RAW database
GRANT USAGE ON DATABASE SHOPSTREAM_RAW
TO ROLE SHOPSTREAM_DBT_ROLE;

GRANT USAGE ON SCHEMA SHOPSTREAM_RAW.ECOMMERCE
TO ROLE SHOPSTREAM_DBT_ROLE;

GRANT SELECT ON ALL TABLES IN SCHEMA SHOPSTREAM_RAW.ECOMMERCE
TO ROLE SHOPSTREAM_DBT_ROLE;

-- Grant future table access in RAW (for tables created later)
GRANT SELECT ON FUTURE TABLES IN SCHEMA SHOPSTREAM_RAW.ECOMMERCE
TO ROLE SHOPSTREAM_DBT_ROLE;

-- Give FULL access to DEV database
-- dbt needs to create, replace, and drop tables/views here
GRANT USAGE ON DATABASE SHOPSTREAM_DEV
TO ROLE SHOPSTREAM_DBT_ROLE;

GRANT USAGE ON ALL SCHEMAS IN DATABASE SHOPSTREAM_DEV
TO ROLE SHOPSTREAM_DBT_ROLE;

GRANT CREATE TABLE ON ALL SCHEMAS IN DATABASE SHOPSTREAM_DEV
TO ROLE SHOPSTREAM_DBT_ROLE;

GRANT CREATE VIEW ON ALL SCHEMAS IN DATABASE SHOPSTREAM_DEV
TO ROLE SHOPSTREAM_DBT_ROLE;

GRANT CREATE STAGE ON ALL SCHEMAS IN DATABASE SHOPSTREAM_DEV
TO ROLE SHOPSTREAM_DBT_ROLE;

-- Grant future schema access in DEV
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE SHOPSTREAM_DEV
TO ROLE SHOPSTREAM_DBT_ROLE;

GRANT CREATE TABLE ON FUTURE SCHEMAS IN DATABASE SHOPSTREAM_DEV
TO ROLE SHOPSTREAM_DBT_ROLE;

GRANT CREATE VIEW ON FUTURE SCHEMAS IN DATABASE SHOPSTREAM_DEV
TO ROLE SHOPSTREAM_DBT_ROLE;


--Step 7
-- Switch to dbt role and verify access
USE ROLE SHOPSTREAM_DBT_ROLE;
USE WAREHOUSE SHOPSTREAM_WH;

-- These should all work without errors
SHOW DATABASES;
USE DATABASE SHOPSTREAM_RAW;
USE SCHEMA ECOMMERCE;
USE DATABASE SHOPSTREAM_DEV;
USE SCHEMA BRONZE;

USE ROLE SHOPSTREAM_DBT_ROLE;
SHOW DATABASES;


SHOW WAREHOUSES;
